import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignOutButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "TeachMate",
  description: "Generated by Kaveesh Khattar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center">
            <Link href="/" className="text-2xl pl-2 font-bold">Teachmate</Link>
            <div className="p-2">
              <SignedOut>
                
                <SignInButton>
                  <Button variant="secondary" className="mr-2">Sign In</Button>
                </SignInButton>
                
                <SignUpButton>
                  <Button>Sign Up</Button>
                </SignUpButton>

              </SignedOut>
            </div>
            <SignedIn>
              
              <div className="flex p-2">
                
                <UserButton />

                <SignOutButton>
                  <Button variant="destructive" className="ml-2">
                    Sign Out
                  </Button>
                </SignOutButton>

                <Link href={"/additional-info"}>
                <Button variant="outline" className="ml-2">
                    Account
                </Button>
                </Link>

              </div>

            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
